import type { ProjectRegistryFile } from "./schema";
import { PROJECT_REGISTRY_SCHEMA_VERSION } from "./schema";

const now = "2026-05-21T00:00:00.000Z";

export function createDefaultProjectRegistry(): ProjectRegistryFile {
  return {
    schemaVersion: PROJECT_REGISTRY_SCHEMA_VERSION,
    createdAt: now,
    updatedAt: now,
    projects: [
      {
        id: "ccc",
        name: "CCC",
        tagline: "Continuity Command Center",
        description:
          "Operational command layer for live telemetry, diagnostics, workflow state, and project handoffs.",
        status: "active",
        domainIds: ["core", "forge", "observatory"],
        linkedPaths: ["C:\\Projects\\CCC"],
        urls: ["https://ccc.thinkcore.io"],
        localSlug: "ccc",
        category: "command",
        continuityPriority: 5,
        operatorIds: ["nexus-7", "fab-0", "deep-1"],
        stack: ["Next.js", "TypeScript", "Tailwind"],
        deploymentCapable: true,
        repoExpected: true,
        systemsAffected: ["command-ui", "telemetry-ingestion", "workflow-surface"],
        highlights: ["Operational facility shell", "Live diagnostics and registry"],
        archivedAt: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "thinkcore",
        name: "ThinkCore",
        tagline: "AI systems lab and public ecosystem",
        description:
          "Umbrella public identity for ThinkCore research, studio projects, media, and live ecosystem routes.",
        status: "active",
        domainIds: ["core", "relay", "forge", "runtime"],
        linkedPaths: ["C:\\Projects\\ThinkCore.io"],
        urls: ["https://thinkcore.io"],
        localSlug: "thinkcore",
        category: "platform",
        continuityPriority: 5,
        operatorIds: ["nexus-7", "fab-0", "bcast-1"],
        stack: ["Static Web", "Public Identity", "Ecosystem Routing"],
        deploymentCapable: true,
        repoExpected: true,
        systemsAffected: ["public-site", "dns", "brand-routing"],
        highlights: ["thinkcore.io public home", "Sibling layers clearly routed"],
        archivedAt: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "liahona",
        name: "Liahona.ai",
        tagline: "Reflective orientation artifact",
        description:
          "Quiet symbolic interface for source-grounded reflection, continuity checkpoints, and artifact-centered orientation.",
        status: "early",
        domainIds: ["core", "relay", "observatory"],
        linkedPaths: ["C:\\Projects\\Liahona"],
        urls: [],
        localSlug: "liahona",
        category: "orientation",
        continuityPriority: 4,
        operatorIds: ["nexus-7", "bcast-1"],
        stack: ["AI", "TypeScript"],
        deploymentCapable: true,
        repoExpected: true,
        systemsAffected: ["orientation-artifact", "source-grounding", "continuity-checkpoints"],
        highlights: ["Artifact-first public surface", "Reflective source boundaries mapped"],
        archivedAt: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "kindex",
        name: "KINDEX",
        tagline: "Knowledge index and retrieval layer",
        description:
          "Structured knowledge indexing across journals, architecture docs, and templated notes.",
        status: "concept",
        domainIds: ["archive", "observatory"],
        linkedPaths: ["C:\\Projects\\SecondBrain"],
        urls: [],
        localSlug: "second-brain",
        category: "archive",
        continuityPriority: 3,
        operatorIds: ["deep-1"],
        stack: ["Markdown", "Index"],
        deploymentCapable: false,
        repoExpected: false,
        systemsAffected: ["vault-index", "memory-lattice"],
        highlights: ["DEEP-1 archivist link", "Import adapters planned"],
        archivedAt: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "field-systems",
        name: "Field Systems",
        tagline: "Scout-oriented offline intelligence",
        description:
          "Portable offline AI, navigation, survival knowledge, and operational resilience.",
        status: "active",
        domainIds: ["core", "archive"],
        linkedPaths: [],
        urls: [],
        localSlug: null,
        category: "knowledge",
        continuityPriority: 4,
        operatorIds: ["scout-6"],
        stack: ["Offline AI", "Navigation"],
        deploymentCapable: false,
        repoExpected: false,
        systemsAffected: ["offline-packs", "field-hardware"],
        highlights: ["SCOUT-6 primary operator", "Offline packs in Archive"],
        archivedAt: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "nlo",
        name: "NLO",
        tagline: "Netherite Legends Odyssey",
        description:
          "Live Minecraft server ecosystem — SMP, PvP, factions, and player economy on Java 1.21.11.",
        status: "live",
        domainIds: ["relay", "runtime", "forge"],
        linkedPaths: [],
        urls: ["https://nlo.gg"],
        localSlug: null,
        category: "game-runtime",
        continuityPriority: 4,
        operatorIds: ["fab-0", "bcast-1"],
        stack: ["Minecraft Java", "Server"],
        deploymentCapable: true,
        repoExpected: true,
        systemsAffected: ["game-server", "community-relay", "economy-runtime"],
        highlights: ["nlo.gg", "FAB-0 deployment watch", "BCAST-1 community relay"],
        ecosystem: {
          platform: "Minecraft Java",
          version: "1.21.11",
          url: "https://nlo.gg",
          modes: ["SMP", "PvP", "Factions", "Player economy"],
          tagline: "Climb the bounty board or build your wealth.",
          metrics: [
            { label: "Players online", value: "—" },
            { label: "Faction territories", value: "—" },
            { label: "Bounty contracts", value: "—" },
            { label: "Economy volume (24h)", value: "—" },
          ],
        },
        archivedAt: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "local-business-web",
        name: "Local Business Web Services",
        tagline: "Local business web presence and delivery",
        description:
          "Client-facing web services, sites, and delivery work for local business operations.",
        status: "active",
        domainIds: ["forge", "relay"],
        linkedPaths: [],
        urls: [],
        localSlug: null,
        category: "platform",
        continuityPriority: 3,
        operatorIds: ["fab-0", "bcast-1"],
        stack: ["Web", "CMS", "Hosting"],
        deploymentCapable: true,
        repoExpected: true,
        systemsAffected: ["client-sites", "hosting", "content-delivery"],
        highlights: ["Client delivery lane", "Outward projection"],
        archivedAt: null,
        createdAt: now,
        updatedAt: now,
      },
    ],
  };
}
